version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /storage/Audiobooks:/audiobooks
      - ~/.audiobookshelf/config:/config
      - ~/.audiobookshelf/metadata:/metadata

